enable GPU health check

diff --git a/gke/nccl-jobset-sweep.yaml b/gke/nccl-jobset-sweep.yaml
--- a/gke/nccl-jobset-sweep.yaml
+++ b/gke/nccl-jobset-sweep.yaml
@@ -50,39 +50,39 @@ spec:
               emptyDir:
                 medium: "Memory"
                 sizeLimit: 250Gi
-            #initContainers:
-            #- name: gpu-healthcheck
-            #  image: "nvidia/cuda:12.8.1-base-ubuntu20.04" #alpine:latest
-            #  command: ["/bin/sh", "-c"]
-            #  args:
-            #  - |
-            #    apk add --no-cache bash  # Install bash
-            #    /bin/bash -c "set -ex
-            #    NUM_GPUS=$(/usr/local/nvidia/bin/nvidia-smi --query-gpu=driver_version --format=csv,noheader,nounits | wc -l)
-            #    if [ \${NUM_GPUS} -lt 8 ]; then
-            #      echo \"Error: Only \${NUM_GPUS} GPUs and expected 8\"
-            #      exit 1
-            #    fi
-            #    gpu_errors=(\$(/usr/local/nvidia/bin/nvidia-smi --query-gpu=ecc.errors.uncorrected.volatile.total --format=csv,noheader,nounits))
-            #    for gpu_index in \${!gpu_errors[@]}; do
-            #        if [ \${gpu_errors[\$gpu_index]} == '[N/A]' ]; then
-            #            echo 'Error: ERR detected in GPU index '\$gpu_index
-            #            exit 1
-            #        elif [ \${gpu_errors[\$gpu_index]} -gt 0 ]; then
-            #            echo 'Error: Unrecoverable ECC errors detected in GPU index '\$gpu_index
-            #            exit 1
-            #        fi
-            #    done
-            #    echo \${NUM_GPUS} GPUs found with no ERR or Unrecoverable ECC errors"
+            initContainers:
+            - name: gpu-healthcheck
+              image: "nvidia/cuda:12.8.1-base-ubuntu20.04" #alpine:latest
+              command: ["/bin/sh", "-c"]
+              args:
+              - |
+                apk add --no-cache bash  # Install bash
+                /bin/bash -c "set -ex
+                NUM_GPUS=$(/usr/local/nvidia/bin/nvidia-smi --query-gpu=driver_version --format=csv,noheader,nounits | wc -l)
+                if [ \${NUM_GPUS} -lt 8 ]; then
+                  echo \"Error: Only \${NUM_GPUS} GPUs and expected 8\"
+                  exit 1
+                fi
+                gpu_errors=(\$(/usr/local/nvidia/bin/nvidia-smi --query-gpu=ecc.errors.uncorrected.volatile.total --format=csv,noheader,nounits))
+                for gpu_index in \${!gpu_errors[@]}; do
+                    if [ \${gpu_errors[\$gpu_index]} == '[N/A]' ]; then
+                        echo 'Error: ERR detected in GPU index '\$gpu_index
+                        exit 1
+                    elif [ \${gpu_errors[\$gpu_index]} -gt 0 ]; then
+                        echo 'Error: Unrecoverable ECC errors detected in GPU index '\$gpu_index
+                        exit 1
+                    fi
+                done
+                echo \${NUM_GPUS} GPUs found with no ERR or Unrecoverable ECC errors"
 
-            #  volumeMounts:
-            #  - name: nvidia
-            #    mountPath: /usr/local/nvidia
-            #  securityContext:
-            #    privileged: true
-            #  env:
-            #  - name: LD_LIBRARY_PATH
-            #    value: /usr/local/nvidia/lib64
+              volumeMounts:
+              - name: nvidia
+                mountPath: /usr/local/nvidia
+              securityContext:
+                privileged: true
+              env:
+              - name: LD_LIBRARY_PATH
+                value: /usr/local/nvidia/lib64
 
             containers:
             - name: tcpxo-daemon
